// Generated by nuxt-auth-sanctum module
import type { SanctumAppConfig } from '../../node_modules/nuxt-auth-sanctum/dist/runtime/types/config.ts';
import type { SanctumGlobalMiddlewarePageMeta } from '../../node_modules/nuxt-auth-sanctum/dist/runtime/types/meta.ts';

declare module 'nuxt/schema' {
    interface AppConfig {
        sanctum?: SanctumAppConfig;
    }
    interface AppConfigInput {
        sanctum?: SanctumAppConfig;
    }
}

declare module '@nuxt/schema' {
    interface AppConfig {
        sanctum?: SanctumAppConfig;
    }
    interface AppConfigInput {
        sanctum?: SanctumAppConfig;
    }
}

declare module '#app' {
    interface PageMeta {
        /**
         * Sanctum global middleware page configuration.
         */
        sanctum?: Partial<SanctumGlobalMiddlewarePageMeta>;
    }
}

declare module '#app/../pages/runtime/composables' {
    interface PageMeta {
        /**
         * Sanctum global middleware page configuration.
         */
        sanctum?: Partial<SanctumGlobalMiddlewarePageMeta>;
    }
}

export {};