// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/12/2026, 1:51:51 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/plugins/**/*.{js,ts,mjs}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/composables/**/*.{js,ts,mjs}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/utils/**/*.{js,ts,mjs}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/vis/Documents/ParagonU/Semester V/CS 397 - Internet of Everything/Final Project/frontend/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;