// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/11/2026, 7:56:07 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/plugins/**/*.{js,ts,mjs}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/composables/**/*.{js,ts,mjs}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/utils/**/*.{js,ts,mjs}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/long/Library/Mobile Documents/com~apple~CloudDocs/Developer/Paragon IU/Semester V/CS 397/Scan2Attend/ScanToAttend-nuxt/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;